### ISSUE TITLE
Upgrading from 1.0rc1 to 9.18.0rc2 seems to be broken

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.upload#102]
After upgrading a site with collective.upload 1.0rc1 to 9.18.0rc2 the profile version is kept in 1.

![selection_024](https://user-images.githubusercontent.com/341393/32238508-19570688-be4f-11e7-92b9-137fcc69a84f.png)
# #

**Comment by idgserpro** [comment]
I don't think that broken, because in 1.0rc1 your metadata.xml was at 1. 

https://github.com/collective/collective.upload/blob/1.0rc1/src/collective/upload/profiles/default/metadata.xml#L3
