### ISSUE TITLE
Cross-site file uploads duplicate images on Chrome

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.upload#11]
Drag and drop an image from one window to another results in a duplicate upload as shown below.

![upload](https://f.cloud.github.com/assets/341393/71894/492bc7de-5ffb-11e2-966d-63144c9a382d.png)

tested on Chromium v23.0.1271.97 running on Ubuntu 12.04 (23.0.1271.97-0ubuntu0.12.04.1).

**Comment by rodfersou** [comment]
@hvelarde here this bug don't happen (also refactored dnd at #94)
