### ISSUE TITLE
Plone 4.3 and JavaScript

### ISSUE THREAD

**Issue by alanschmitz** [collective/collective.upload#22]
I installed Plone 4.3 using the Windows installer from plone.org, added collective.upload to the buildout.cfg, and ran buildout.  After installing it with the quick installer, I can see two extra lines on the folder contents view.  They start with "Add files or images" and "Progress Bar".  When I browse for a file and click on start upload, the page reloads, and I get a KeyError: 'title[]' As far as I can tell none of the JavaScript for the upload is getting run.

I've tried clearing my browser cache, using the save button in the JavaScript Resource Registry, and changing all of the Resource Registries to Development mode.  While it's in Development Mode, this file returns a 404 in the web console: 

/++resource++collective.upload/jquery.fileupload-ui.css

I've tried in Firefox 21 and Chrome 27.  Does collective.upload work with Plone 4.3?

**Comment by hvelarde** [comment]
this has to be already fixed.
