### ISSUE TITLE
Add field to set the creator

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.upload#34]
We need to provide an easy way to set the creator, the same we are doing with the title and description.

**Comment by hvelarde** [comment]
@agnogueira could you please provide a mockup of the new modal?

this is related with #33

**Comment by agnogueira** [comment]
![upload](https://cloud.githubusercontent.com/assets/1030139/8502700/885eaf72-218a-11e5-950d-bfd4822bd8b6.png)
