### ISSUE TITLE
read metadata form IPTC IIM properties if present

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.upload#6]
when uploading images it would be a nice feature to read the embedded IPTC IIM metadata if it's present.

this should be implemented in JavaScript; here is an example on [how to extract EXIF metadata](https://github.com/jseidelin/exif-js/blob/master/exif.js) that could be worth reviewing.

we only need to do this for the **title**, **description** and **creator** fields; some other fields could be server-side processed if needed using the [unweb.iptc](http://pypi.python.org/pypi/unweb.iptc) package.
- **title** should be read from Object Name record (2:05)
- **description** should be read from Caption/Abstract (2:120)
- **creator** should be read from By-line (2:80)

useful resources:
- [quick reference on the IPTC IMM](http://www.exiv2.org/iptc.html)
- [complete IPTC IMM specification](http://www.iptc.org/std/IIM/4.1/specification/IPTC-IIM-Schema4XMP-1.0-spec_1.pdf)

**Comment by petri** [comment]
You might want to also check [collective.documentfile](https://github.com/collective/collective.documentfile) - it's developed to provide a common mechanism for automatic copying over metadata (and thumbnail/cover -> lead image) from various kinds of uploaded files to Plone content. While my immediate use case was MS Office and PDF files (hence the package naming), it is and will be document/file type agnostic.
