### ISSUE TITLE
Shorten the "add files or images..." label

### ISSUE THREAD

**Issue by petri** [collective/collective.upload#67]
See screenshot below: the label is too long, it gets wrapped to second line when there are any portlets left (or right). Ugly.

<img width="1239" alt="nayttokuva 2016-05-31 kello 17 37 18" src="https://cloud.githubusercontent.com/assets/64672/15678382/d70f4b22-2756-11e6-92ab-711050491e92.png">

Maybe just "choose files"? Images are files after all, and "add" is potentially somewhat ambiguous.

**Comment by hvelarde** [comment]
I think there's plenty of space to fix this CC @agnogueira

**Comment by hvelarde** [comment]
fixed in #89
