### ISSUE TITLE
Plone 5 compatibility

### ISSUE THREAD

**Issue by misaelnieto** [collective/collective.upload#99]
Hi.

I want to use collective.upload in Plone 5. I still remember some Plone and Zope stuff so I could send a PR if I make it work on it. Anyone interested?

**Comment by pbauer** [comment]
I don't really see what additional benefit this package offers compared to the default upload in Plone 5 (which does multiple uploads of files and images). If there are additional features it might be better to enhance the default feature.

**Comment by misaelnieto** [comment]
Ohh I see now. Yes, it's better to use Plone's file uploader.
